In [2]:
#import thu vien
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("/home/binperdok/KLTN2026/Data/du_lieu_ai_day_du.csv")

In [4]:
df.head(5)

,title,summary,link,published,label,content
0,Elon Musk sáp nhập xAI vào SpaceX,"<a href=""https://vnexpress.net/elon-musk-sap-n...",https://vnexpress.net/elon-musk-sap-nhap-xai-v...,"Tue, 03 Feb 2026 06:55:30 +0700",NaN,"""Những tiến bộ hiện tại của AI phụ thuộc vào t..."
1,Kỹ sư Gen Z Việt gọi vốn một triệu USD cho sta...,"<a href=""https://vnexpress.net/ky-su-gen-z-vie...",https://vnexpress.net/ky-su-gen-z-viet-goi-von...,"Tue, 03 Feb 2026 05:00:00 +0700",NaN,"Nguyễn Đức Trung, đang học và làm việc tại Đức..."
2,Những dấu mốc trong ba năm của ngành bán dẫn V...,"<a href=""https://vnexpress.net/nhung-dau-moc-t...",https://vnexpress.net/nhung-dau-moc-trong-ba-n...,"Mon, 02 Feb 2026 09:00:00 +0700",NaN,"Có lịch sử gần 50 năm, nhưng lĩnh vực bán dẫn ..."
3,Blue Origin dừng hoạt động du lịch vũ trụ,"<a href=""https://vnexpress.net/blue-origin-dun...",https://vnexpress.net/blue-origin-dung-hoat-do...,"Mon, 02 Feb 2026 07:47:21 +0700",NaN,Blue Origin cuối tháng 1 thông báo dừng các ch...
4,SpaceX xin phóng một triệu vệ tinh làm trung t...,"<a href=""https://vnexpress.net/spacex-xin-phon...",https://vnexpress.net/spacex-xin-phong-mot-tri...,"Sun, 01 Feb 2026 15:00:00 +0700",NaN,Theo hồ sơ SpaceX nộp lên Ủy ban Truyền thông ...

,Title_VN,content_VN
0,PRX Part 3 — Đào tạo một Text-to-Image Model t...,Chào mừng trở lại 👋 Trong hai bài viết trước (...
1,Mixture of Experts (MoEs) trong Transformers,"Trong vài năm qua, việc mở rộng quy mô các mô ..."
2,Huấn luyện các mô hình AI với Unsloth và Huggi...,Bạn sẽ cầnChạy JobCài đặt SkillClaude CodeCode...
3,Transformers.js v4 Preview: Hiện đã có mặt trê...,Cải thiện Hiệu suất & Thời gian chạy\nTái cấu ...
4,Mô hình Holo2 mới của Công ty H dẫn đầu trong ...,Hai tháng kể từ khi phát hành đợt đầu tiên của...

,Title,content
0,PRX Part 3 — Đào tạo một Text-to-Image Model t...,Chào mừng trở lại 👋 Trong hai bài viết trước (...
1,Mixture of Experts (MoEs) trong Transformers,"Trong vài năm qua, việc mở rộng quy mô các mô ..."
2,Huấn luyện các mô hình AI với Unsloth và Huggi...,Bạn sẽ cầnChạy JobCài đặt SkillClaude CodeCode...
3,Transformers.js v4 Preview: Hiện đã có mặt trê...,Cải thiện Hiệu suất & Thời gian chạy\nTái cấu ...
4,Mô hình Holo2 mới của Công ty H dẫn đầu trong ...,Hai tháng kể từ khi phát hành đợt đầu tiên của...

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    237 non-null    object
 1   content  237 non-null    object
dtypes: object(2)
memory usage: 5.9+ KB

In [5]:
df[['title', 'content']] = df[['title', 'content']].replace('', np.nan)
df = df.dropna(subset=['title', 'content'])

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 237 entries, 0 to 236
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    237 non-null    object
 1   content  237 non-null    object
dtypes: object(2)
memory usage: 5.6+ KB

In [20]:
df = df.assign(label="DEEP DIVE")

In [21]:
df.head()

,title,content,label
0,PRX Part 3 — Đào tạo một Text-to-Image Model t...,Chào mừng trở lại 👋 Trong hai bài viết trước (...,DEEP DIVE
1,Mixture of Experts (MoEs) trong Transformers,"Trong vài năm qua, việc mở rộng quy mô các mô ...",DEEP DIVE
2,Huấn luyện các mô hình AI với Unsloth và Huggi...,Bạn sẽ cầnChạy JobCài đặt SkillClaude CodeCode...,DEEP DIVE
3,Transformers.js v4 Preview: Hiện đã có mặt trê...,Cải thiện Hiệu suất & Thời gian chạy\nTái cấu ...,DEEP DIVE
4,Mô hình Holo2 mới của Công ty H dẫn đầu trong ...,Hai tháng kể từ khi phát hành đợt đầu tiên của...,DEEP DIVE

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 237 entries, 0 to 236
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    237 non-null    object
 1   content  237 non-null    object
 2   label    237 non-null    object
dtypes: object(3)
memory usage: 7.4+ KB

In [9]:
# Xóa hàng có title là null/NaN
df = df.dropna(subset=['content'])

# Xóa hàng có title là empty hoặc "Không thể trích xuất nội dung"
INVALID_TITLES = {"", "Không thể trích xuất nội dung"}
df = df[~df['content'].str.strip().isin(INVALID_TITLES)]

# Xóa hàng có title quá ngắn (dưới 50 ký tự)
df = df[df['content'].str.split().str.len() >= 50]

df = df.reset_index(drop=True)
print(f"Còn lại: {len(df)} hàng")

Còn lại: 317 hàng

In [10]:
df.head()

,title,summary,link,published,label,content
0,Elon Musk sáp nhập xAI vào SpaceX,"<a href=""https://vnexpress.net/elon-musk-sap-n...",https://vnexpress.net/elon-musk-sap-nhap-xai-v...,"Tue, 03 Feb 2026 06:55:30 +0700",NaN,"""Những tiến bộ hiện tại của AI phụ thuộc vào t..."
1,Kỹ sư Gen Z Việt gọi vốn một triệu USD cho sta...,"<a href=""https://vnexpress.net/ky-su-gen-z-vie...",https://vnexpress.net/ky-su-gen-z-viet-goi-von...,"Tue, 03 Feb 2026 05:00:00 +0700",NaN,"Nguyễn Đức Trung, đang học và làm việc tại Đức..."
2,Những dấu mốc trong ba năm của ngành bán dẫn V...,"<a href=""https://vnexpress.net/nhung-dau-moc-t...",https://vnexpress.net/nhung-dau-moc-trong-ba-n...,"Mon, 02 Feb 2026 09:00:00 +0700",NaN,"Có lịch sử gần 50 năm, nhưng lĩnh vực bán dẫn ..."
3,Blue Origin dừng hoạt động du lịch vũ trụ,"<a href=""https://vnexpress.net/blue-origin-dun...",https://vnexpress.net/blue-origin-dung-hoat-do...,"Mon, 02 Feb 2026 07:47:21 +0700",NaN,Blue Origin cuối tháng 1 thông báo dừng các ch...
4,SpaceX xin phóng một triệu vệ tinh làm trung t...,"<a href=""https://vnexpress.net/spacex-xin-phon...",https://vnexpress.net/spacex-xin-phong-mot-tri...,"Sun, 01 Feb 2026 15:00:00 +0700",NaN,Theo hồ sơ SpaceX nộp lên Ủy ban Truyền thông ...

In [12]:
df.to_csv("/home/binperdok/KLTN2026/Data/TEST_DATA_NOT_Label.csv", index = False, encoding='utf-8-sig')