In [15]:
#import thu vien
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/home/binperdok/KLTN2026/Data/data_label_deepdive/data_deep_dive_2026_03_07_full_vietnamese.csv")

In [3]:
df.head(5)

,Source,Title,Link,Date,content,Title_VN,content_VN
0,huggingface.co,PRX Part 3 — Training a Text-to-Image Model in...,https://huggingface.co/blog/Photoroom/prx-part3,"Tue, 03 Mar 2026 16:50:49 GMT",Welcome back 👋 In the last two posts (Part 1an...,PRX Part 3 — Đào tạo một Text-to-Image Model t...,Chào mừng trở lại 👋 Trong hai bài viết trước (...
1,huggingface.co,Mixture of Experts (MoEs) in Transformers,https://huggingface.co/blog/moe-transformers,"Thu, 26 Feb 2026 00:00:00 GMT","Over the past few years, scaling dense languag...",Mixture of Experts (MoEs) trong Transformers,"Trong vài năm qua, việc mở rộng quy mô các mô ..."
2,huggingface.co,Train AI models with Unsloth and Hugging Face ...,https://huggingface.co/blog/unsloth-jobs,"Fri, 20 Feb 2026 00:00:00 GMT",You will needRun the JobInstalling the SkillCl...,Huấn luyện các mô hình AI với Unsloth và Huggi...,Bạn sẽ cầnChạy JobCài đặt SkillClaude CodeCode...
3,huggingface.co,Transformers.js v4 Preview: Now Available on NPM!,https://huggingface.co/blog/transformersjs-v4,"Mon, 09 Feb 2026 00:00:00 GMT",Performance & Runtime ImprovementsRepository R...,Transformers.js v4 Preview: Hiện đã có mặt trê...,Cải thiện Hiệu suất & Thời gian chạy\nTái cấu ...
4,huggingface.co,H Company's new Holo2 model takes the lead in ...,https://huggingface.co/blog/Hcompany/introduci...,"Tue, 03 Feb 2026 17:40:14 GMT",Two months since releasing our first batch of ...,Mô hình Holo2 mới của Công ty H dẫn đầu trong ...,Hai tháng kể từ khi phát hành đợt đầu tiên của...

In [6]:
# Ví dụ nếu tên cột chuẩn là:
df.drop(columns=['Source', 'Title', 'Link', 'Date', 'content'], inplace=True)

In [8]:
df.head()

,Title_VN,content_VN
0,PRX Part 3 — Đào tạo một Text-to-Image Model t...,Chào mừng trở lại 👋 Trong hai bài viết trước (...
1,Mixture of Experts (MoEs) trong Transformers,"Trong vài năm qua, việc mở rộng quy mô các mô ..."
2,Huấn luyện các mô hình AI với Unsloth và Huggi...,Bạn sẽ cầnChạy JobCài đặt SkillClaude CodeCode...
3,Transformers.js v4 Preview: Hiện đã có mặt trê...,Cải thiện Hiệu suất & Thời gian chạy\nTái cấu ...
4,Mô hình Holo2 mới của Công ty H dẫn đầu trong ...,Hai tháng kể từ khi phát hành đợt đầu tiên của...

In [10]:
df.rename(columns = {"Title_VN" : "Title", "content_VN": "content"}, inplace = True )

In [11]:
df.head(5)

,Title,content
0,PRX Part 3 — Đào tạo một Text-to-Image Model t...,Chào mừng trở lại 👋 Trong hai bài viết trước (...
1,Mixture of Experts (MoEs) trong Transformers,"Trong vài năm qua, việc mở rộng quy mô các mô ..."
2,Huấn luyện các mô hình AI với Unsloth và Huggi...,Bạn sẽ cầnChạy JobCài đặt SkillClaude CodeCode...
3,Transformers.js v4 Preview: Hiện đã có mặt trê...,Cải thiện Hiệu suất & Thời gian chạy\nTái cấu ...
4,Mô hình Holo2 mới của Công ty H dẫn đầu trong ...,Hai tháng kể từ khi phát hành đợt đầu tiên của...

In [12]:
df.rename(columns={"Title": "title"}, inplace = True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    237 non-null    object
 1   content  237 non-null    object
dtypes: object(2)
memory usage: 5.9+ KB

In [16]:
df[['title', 'content']] = df[['title', 'content']].replace('', np.nan)
df = df.dropna(subset=['title', 'content'])

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 237 entries, 0 to 236
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    237 non-null    object
 1   content  237 non-null    object
dtypes: object(2)
memory usage: 5.6+ KB

In [20]:
df = df.assign(label="DEEP DIVE")

In [21]:
df.head()

,title,content,label
0,PRX Part 3 — Đào tạo một Text-to-Image Model t...,Chào mừng trở lại 👋 Trong hai bài viết trước (...,DEEP DIVE
1,Mixture of Experts (MoEs) trong Transformers,"Trong vài năm qua, việc mở rộng quy mô các mô ...",DEEP DIVE
2,Huấn luyện các mô hình AI với Unsloth và Huggi...,Bạn sẽ cầnChạy JobCài đặt SkillClaude CodeCode...,DEEP DIVE
3,Transformers.js v4 Preview: Hiện đã có mặt trê...,Cải thiện Hiệu suất & Thời gian chạy\nTái cấu ...,DEEP DIVE
4,Mô hình Holo2 mới của Công ty H dẫn đầu trong ...,Hai tháng kể từ khi phát hành đợt đầu tiên của...,DEEP DIVE

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 237 entries, 0 to 236
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    237 non-null    object
 1   content  237 non-null    object
 2   label    237 non-null    object
dtypes: object(3)
memory usage: 7.4+ KB

In [23]:
df.label.value_counts()

label
DEEP DIVE    237
Name: count, dtype: int64

In [24]:
df.to_csv("/home/binperdok/KLTN2026/Data/data_label_deepdive/final_09_03_2026.csv", index = False, encoding='utf-8-sig')